name: netplan-test
base: core18
version: '0.1'
summary: netplan test
description: |
  This is my-snap's description. You have a paragraph or two to tell the

grade: stable
confinement: strict

parts:
    netplan:
        plugin: nil
        stage-packages:
            - netplan.io
        stage:
            - lib/netplan
            - usr/sbin/netplan
            - usr/share/netplan

apps:
    netplan:
        adapter: none
        command: $SNAP/usr/sbin/netplan
        environment:
            PYTHONPATH: /usr/lib/python3/dist-packages:$PYTHONPATH
        plugs:
            - network
            - network-bind
            - network-setup-control
