name: test-ppa-short
base: core18
version: 'test1'
summary: test
description: test
grade: stable
confinement: strict

parts:

  test-git:
    plugin: nil
    source: https://github.com/ubuntu/yaru.git
    source-depth: 1
    source-commit: c324c18dc78f7b33b660b14797db993d1da852b5

apps:
    test-ppa:
      command: test-ppa
