name: test-ppa-long
base: core18
version: 'test1'
summary: test
description: test
grade: stable
confinement: strict

parts:
  test-ppa:
    plugin: nil
    stage-packages:
      - test-ppa

apps:
    test-ppa:
      command: test-ppa

package-management:
  repositories:
    - source: http://ppa.launchpad.net/cjp256/test-ppa/ubuntu
      gpg-public-key-id: 590CA3D8E4826565BE3200526A634116E00F4C82
