name: fake-interp-test
base: core18
version: '0.1'
summary: interpreter on host, but not in base
description: |
  This is my-snap's description. You have a paragraph or two to tell the

grade: stable
confinement: strict

parts:
    fake-interp-test:
        plugin: dump
        source: test
        override-build: |
          snapcraftctl build
          cp /bin/bash /bin/fake-interp

apps:
    fake-interp-test:
        command: fake-interp-test
